name: Terraform Deploy Pipeline

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: "Docker image tag to deploy"
        required: true
        type: string

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to AWS
        uses: aws-actions/configure-aws-credentials@v6.3.0
        with:
          role-to-assume: arn:aws:iam::446503125863:role/threatmod-github-actions-iam-role
          aws-region: eu-west-2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: ./infra
        run: terraform init

      - name: Terraform Plan
        working-directory: ./infra
        run: terraform plan -var="image_tag=${{ inputs.image_tag }}"

      - name: Terraform Apply
        working-directory: ./infra
        run: terraform apply -auto-approve -var="image_tag=${{ inputs.image_tag }}"
      - name: Post-Deploy Health Check
        run: curl --fail https://tm.shabnamkhan.tech/health   